<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Entity Framework Core database provider that remotes LINQ queries and change-tracking over a wire protocol.</Description>
    <RootNamespace>InfoCarrier.Core</RootNamespace>
    <AssemblyName>InfoCarrier.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfoCarrier.Core.Abstractions\InfoCarrier.Core.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

</Project>
