image: Visual Studio 2019

environment:
  Test__SqlServer__DefaultConnection: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!

services: mssql2017

before_build:
  - dotnet --info
  - dotnet tool restore

build_script:
  - dotnet flubu build
  - dotnet flubu pack

test_script:
  - dotnet flubu test

artifacts:
  path: artifacts
