// Licensed under the MIT license. See license.txt file in the project root for license information.

using InfoCarrier.Core.FunctionalTests.TestUtilities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.TestUtilities;

namespace InfoCarrier.Core.FunctionalTests;

/// <summary>
///     <c>StoreGeneratedFixupTestBase</c> on Tier A.
/// </summary>
/// <remarks>
///     Fixup between entities whose keys the store generates — the case where the client's key
///     is temporary and cannot travel (wire-protocol W2, plan S3c-9).
/// </remarks>
public class StoreGeneratedFixupInfoCarrierTest(StoreGeneratedFixupInfoCarrierTest.InfoCarrierFixture fixture)
    : StoreGeneratedFixupTestBase<StoreGeneratedFixupInfoCarrierTest.InfoCarrierFixture>(fixture)
{
    /// <summary>
    ///     The backend is EF's InMemory provider, which does not enforce foreign keys — so this
    ///     answers exactly what <c>StoreGeneratedFixupInMemoryTest</c> answers. It is the *store*
    ///     being described, and on this tier the store is InMemory.
    /// </summary>
    protected override bool EnforcesFKs
        => false;

    /// <summary>
    ///     Empties the shared store after every test.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         The base wraps each test in a transaction and relies on the rollback to undo it.
    ///         The backend here is EF's InMemory provider, which does not do transactions, so
    ///         nothing is undone — and this model's keys are composite and <em>not</em>
    ///         store-generated by convention, so every test creates a `Category` keyed
    ///         `(0, Guid.Empty)`. The second one to save collides: "an item with the same key has
    ///         already been added".
    ///     </para>
    ///     <para>
    ///         Established by running a failing test on its own, where it passes — so the failure
    ///         is the previous test's leftovers and not this one's behaviour.
    ///         <c>GraphUpdatesInfoCarrierTest</c> and <c>OptimisticConcurrencyInfoCarrierTest</c>
    ///         already clean for exactly this reason; `finally`, because a failing test dirties
    ///         the store the same way a passing one does.
    ///     </para>
    /// </remarks>
    protected override async Task ExecuteWithStrategyInTransactionAsync(Func<DbContext, Task> testOperation)
    {
        try
        {
            await base.ExecuteWithStrategyInTransactionAsync(testOperation);
        }
        finally
        {
            InfoCarrierBackendTestStore backend = ((InfoCarrierTestStore)Fixture.TestStore).Backend;
            using DbContext context = backend.CreateDbContext();
            await backend.CleanAsync(context);
        }
    }

    public class InfoCarrierFixture : StoreGeneratedFixupFixtureBase
    {
        private ITestStoreFactory _testStoreFactory;

        protected override string StoreName
            => "StoreGeneratedFixupInfoCarrierTest";

        protected override ITestStoreFactory TestStoreFactory
            => _testStoreFactory ??= InfoCarrierTestStoreFactory.Create(
                InfoCarrierTestStoreFactory.InMemory,
                ContextType,
                (modelBuilder, context) => OnModelCreating(modelBuilder, context));
    }
}
