// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Northwind.Client.CompiledModel
{
    public partial class NorthwindContextModel
    {
        private NorthwindContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("415d6e58-8694-432b-b71e-650c5411f4ab"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var category = CategoryEntityType.Create(this);
            var customer = CustomerEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var orderDetail = OrderDetailEntityType.Create(this);
            var product = ProductEntityType.Create(this);

            OrderEntityType.CreateForeignKey1(order, customer);
            OrderDetailEntityType.CreateForeignKey1(orderDetail, order);
            OrderDetailEntityType.CreateForeignKey2(orderDetail, product);

            CategoryEntityType.CreateAnnotations(category);
            CustomerEntityType.CreateAnnotations(customer);
            OrderEntityType.CreateAnnotations(order);
            OrderDetailEntityType.CreateAnnotations(orderDetail);
            ProductEntityType.CreateAnnotations(product);

            AddAnnotation("ProductVersion", "10.0.0");
            AddAnnotation("Proxies:ChangeTracking", false);
            AddAnnotation("Proxies:CheckEquality", false);
            AddAnnotation("Proxies:LazyLoading", true);
        }
    }
}
