// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Northwind.Client.CompiledModel;
using Northwind.Shared;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(NorthwindContext), typeof(NorthwindContextModel))]
