// Licensed under the MIT license. See license.txt file in the project root for license information.

using InfoCarrier.Core;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.FluentUI.AspNetCore.Components;
using Northwind.Client;
using Northwind.Client.Transport;
using Northwind.Client.Wire;
using Northwind.Shared;

// ---------------------------------------------------------------------------------------------
// FIRST, before anything can touch the compiled model.
//
// EF's generated model runs its own initialization on a `new Thread(..., 10 * 1024 * 1024)` -- a
// deliberately large stack, because a big model can overflow the default one (EF issue 31751).
// WebAssembly has no threads, so merely *reading* `NorthwindContextModel.Instance` throws
// `PlatformNotSupportedException: Arg_PlatformNotSupported` from `Thread.Start`, wrapped in a
// `TypeInitializationException`, and the app never renders at all.
//
// This switch is EF's own escape hatch, emitted into the generated file: it initializes the model
// inline on the calling thread instead. The large stack buys nothing for five entity types.
//
// Set in code rather than in the csproj so that a reader of this sample meets the explanation at
// the point it matters.
// ---------------------------------------------------------------------------------------------
AppContext.SetSwitch("Microsoft.EntityFrameworkCore.Issue31751", true);

WebAssemblyHostBuilder builder = WebAssemblyHostBuilder.CreateDefault(args);

builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddFluentUIComponents();
builder.Services.AddSingleton<WireLog>();

// ---------------------------------------------------------------------------------------------
// This is the whole client wiring, and it is the point of the sample. Nothing below configures a
// database, because the browser has none. Everything singleton: WebAssembly is one user in one
// tab, so a scope would be ceremony without a lifetime behind it.
// ---------------------------------------------------------------------------------------------

// Same origin as the page. The server hosts these files (spec §3.4), so there is one URL, one
// launch profile and no CORS.
builder.Services.AddSingleton(_ => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

builder.Services.AddSingleton<IInfoCarrierSerializer, SystemTextJsonInfoCarrierSerializer>();

builder.Services.AddSingleton<IInfoCarrierClient>(services =>
{
    var serializer = services.GetRequiredService<IInfoCarrierSerializer>();

    IInfoCarrierTransport transport = new HttpInfoCarrierTransport(
        services.GetRequiredService<HttpClient>(), serializer);

    // The inspector rides on the seam rather than inside the transport, which is what keeps
    // HttpInfoCarrierTransport free of sample types and therefore promotable by a file move.
    transport = new InspectingTransport(transport, serializer, services.GetRequiredService<WireLog>());

    return new TransportInfoCarrierClient(transport, serializer);
});

// A factory, not a context: each page owns its own unit of work, which is exactly what the Order
// page is there to show. A DbContext held for the lifetime of the app would accumulate tracked
// entities across pages and make "one SaveChanges for several edits" mean nothing.
builder.Services.AddDbContextFactory<NorthwindContext>((services, options) => options
    .UseInfoCarrier(services.GetRequiredService<IInfoCarrierClient>())

    // The model, already built (spec §7 step 2). Generated by `dotnet ef dbcontext optimize` --
    // see samples/README.md for the command and why the SERVER is its startup project -- so the
    // browser does not build one by reflection at start-up, which is both a start-up cost and the
    // single largest reason a trimmed build would need types kept alive.
    //
    // Called explicitly rather than relying on auto-discovery, deliberately: that mechanism keys
    // off an assembly attribute in the DbContext's OWN assembly, and NorthwindContext lives in
    // Northwind.Shared while the compiled model belongs to this client. `dotnet ef` warns about
    // exactly that, and UseModel is the answer it offers.
    .UseModel(Northwind.Client.CompiledModel.NorthwindContextModel.Instance)

    // Kept for MODEL PARITY, not for lazy loading, and the difference was measured (M8-14).
    //
    // Proxies work here -- Castle DynamicProxy emits types fine under the Mono interpreter, which
    // is what spec §3.2 was worried about, and the Customers page reports `CustomerProxy` to prove
    // it. But *automatic* lazy loading still cannot work in a browser: a navigation property getter
    // is synchronous, so it must block on the HTTP round trip, and a single-threaded WebAssembly
    // runtime cannot block. `order.Customer` throws "Cannot wait on monitors on this runtime" --
    // after the request has already gone out. `ILazyLoader.Load()` is synchronous too, so §3.2's
    // recorded fallback fails identically. The Order page therefore uses `LoadAsync`.
    //
    // This stays configured because the SERVER configures it, and proxies add a model convention:
    // the two models must agree about everything the wire names (A49).
    .UseLazyLoadingProxies());

await builder.Build().RunAsync();
